version: "3.7"
services:
  db:
    build: development/db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - DB_APP_NAME=bep2-huland-casino
      - DB_APP_USER=bep2-huland-casino
      - DB_APP_PASS=bep2-huland-casino
    volumes:
      - "./data:/var/data/db"